### ISSUE TITLE
Plot copy will not read space on networked drives?

### ISSUE THREAD

**Issue by 136FA** [cracklingice/Plot-Copy-Multi#1]
Either I am dense or this will not read networked drives storage. I confirmed it does work with local storage, but when using networked storage as the destination either via dir:\ or \\ipadd\dir\ it will always say the drive is full.

**Comment by cracklingice** [comment]
Unfortunately, I don't have network drives to test with.  I'm assuming that you are saying that in the command prompt if you do dir followed by the letter of the mapped drive ( dir P: ) it will report 0 bytes free?
Would you please reply with the output of wmic logicaldisk where "DeviceID='P:'" get FreeSpace
Substitute P: with the letter of your mapped drive followed by the colon of course.  :)

**Comment by cracklingice** [comment]
I spoke with another person using the batch file and it is working fine for them.  Do you have the network share mapped to a drive letter?  If not, map the network share and try again.
